FROM azul/zulu-openjdk-alpine:17
#ARG JAR_FILE=build/libs/*.jar
ARG JAR_FILE=./*.jar
ARG YML_FILE=./application-dev.yml
COPY ${JAR_FILE} app.jar
COPY ${YML_FILE} application-dev.yml
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=dev","/app.jar"]
